services:
  frontend:
    build : ./MyBookstore102
    ports : 
      - "3001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s      # ตรวจสอบทุก 30 วินาที
      timeout: 10s       # รอ response ไม่เกิน 10 วินาที
      retries: 3         # ถ้าล้มเหลว 3 ครั้งติดถือว่า unhealthy
      start_period: 40s  # ให้เวลา 40 วินาทีสำหรับ startup